<?php

require("header.phtml");
?>

<table class="container" style="background-color: #fff;margin-top: 25px;box-shadow: 0 0 0 3px #e9e9e9;border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: inherit;width: 589px;margin: 0 auto;">
    <tr style="padding: 0;vertical-align: top;text-align: left;">
        <td style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 8px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">

            <!-- content start -->
            <table class="row" style="border-spacing: 0;border-collapse: collapse;padding: 0px;vertical-align: top;text-align: left;width: 100%;position: relative;display: block;">
                <tr style="padding: 0;vertical-align: top;text-align: left;">
                    <td class="wrapper last" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-right: 0px;border-collapse: collapse !important;">

                        <table class="twelve columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 589px;">
                            <tr style="padding: 0;vertical-align: top;text-align: left;">
                                <td style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">
                                    <img src="https://www.mariadebarro.com.br/homolog/web-files/emails/images/feliz_aniversario.jpg" alt="" style="float: none;margin: 0 auto 20px;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;width: auto;max-width: 100%;clear: both;display: block;">
                                </td>
                                <td class="expander" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0 !important;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;visibility: hidden;width: 0px;border-collapse: collapse !important;"></td>
                            </tr>
                        </table>

                    </td>
                </tr>
            </table>

            <table class="row" style="border-spacing: 0;border-collapse: collapse;padding: 0px;vertical-align: top;text-align: left;width: 100%;position: relative;display: block;">
                <tr style="padding: 0;vertical-align: top;text-align: left;">
                    <td class="wrapper offset-by-one" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-left: 50px;border-collapse: collapse !important;">

                        <table class="two columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 80px;">
                            <tr style="padding: 0;vertical-align: top;text-align: left;">
                                <td style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">
                                    <img src="https://www.mariadebarro.com.br/homolog/web-files/emails/images/cadastro_06.jpg" alt="" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;width: auto;max-width: 100%;float: left;clear: both;display: block;">
                                </td>
                                <td class="expander" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0 !important;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;visibility: hidden;width: 0px;border-collapse: collapse !important;"></td>
                            </tr>
                        </table>

                    </td>
                    <td class="wrapper last" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-right: 0px;border-collapse: collapse !important;">

                        <table class="eight columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 380px;">
                            <tr style="padding: 0;vertical-align: top;text-align: left;">
                                <td style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">
                                    <div style='font-size: 14px;'>
                                        <h2><?php echo $view_nome; ?>,</h2>
                                        <div>A <strong>Maria de Barro</strong> e toda a sua equipe deseja que este dia <strong><?php echo $view_dia; ?> de <?php echo $view_mes; ?> de <?php echo $view_ano; ?></strong> seja repleto de felicidades e vitórias em sua vida!<div><br/>
                                                <div>Para sua próxima compra estamos enviando um <strong>PRESENTE</strong>, no valor de <strong>10%.</strong><div><br/>
                                                        <div>Segue abaixo o código do <strong>CUPOM DE DESCONTOS</strong>:<div><br/>
                                                                <div style='boder: 1px solid #000; padding: 3%'><h1><?php echo $view_codigo; ?></h1><div><br/>
                                                                        <div><a href='https://www.mariadebarro.com.br/'><img src='https://www.mariadebarro.com.br/homolog/web-files/img/logo.png' alt='Maria de Barro' title='Maria de Barro' border='0'/></a></div><br/>
                                                                        <div><strong>* Não responder a este e-mail</strong></div><br/>
                                                                    </div>
                                </td>
                                <td class="expander" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0 !important;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;visibility: hidden;width: 0px;border-collapse: collapse !important;"></td>
                            </tr>
                        </table>

                    </td>
                </tr>
            </table>

            <table class="row" style="border-spacing: 0;border-collapse: collapse;padding: 0px;vertical-align: top;text-align: left;width: 100%;position: relative;display: block;">
                <tr style="padding: 0;vertical-align: top;text-align: left;">
                    <td class="wrapper last" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-right: 0px;border-collapse: collapse !important;">

                        <table class="twelve columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 589px;">
                            <tr style="padding: 0;vertical-align: top;text-align: left;">
                                <td style="padding-bottom: 0;word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;"> 
                                    <img src="https://www.mariadebarro.com.br/homolog/web-files/emails/images/cadastro_11.jpg" alt="" usemap="#mariadebarro" width="589" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;width: auto;max-width: 100%;float: left;clear: both;display: block;">
                                    <map name="mariadebarro">
                                        <area share="rect" coords="125,18,457,60" alt="Clique aqui para acessar o site" href="https://www.mariadebarro.com.br" target="_blank"></area>
                                        <area share="rect" coords="90,123,308,142" alt="Facebook" href="https://www.facebook.com/mariadebarroacessorios" target="_blank"></area>
                                        <area share="rect" coords="337,123,481,143" alt="Instagram" href="http://instagram.com/mariadebarro" target="_blank"></area>
                                        <area share="rect" coords="0,157,588,298" alt="Maria de Barro" href="https://www.mariadebarro.com.br" target="_blank"></area>
                                    </map>
                                </td>
                            </tr>
                        </table>

                    </td>
                </tr>
            </table>

            <!-- container end below -->
        </td>
    </tr>
</table>

<?php

require("footer.phtml");

