<?php
require("header.phtml");
?>
<table class="container" style="background-color: #fff;margin-top: 25px;box-shadow: 0 0 0 3px #e9e9e9;border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: inherit;width: 589px;margin: 0 auto;">
    <tr style="padding: 0;vertical-align: top;text-align: left;">
        <td style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 8px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">

            <!-- content start -->
            <table class="row" style="border-spacing: 0;border-collapse: collapse;padding: 0px;vertical-align: top;text-align: left;width: 100%;position: relative;display: block;">
                <tr style="padding: 0;vertical-align: top;text-align: left;">
                    <td class="wrapper last" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-right: 0px;border-collapse: collapse !important;">

                        <table class="twelve columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 589px;">
                            <tr style="padding: 0;vertical-align: top;text-align: left;">
                                <td style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">
                                    <img src="<?php echo $_SERVER['EMAIL_IMG_FOLDER']; ?>/cadastro_03.jpg" alt="" style="float: none;margin: 0 auto 20px;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;width: auto;max-width: 100%;clear: both;display: block;">
                                </td>
                                <td class="expander" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0 !important;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;visibility: hidden;width: 0px;border-collapse: collapse !important;"></td>
                            </tr>
                        </table>

                    </td>
                </tr>
            </table>

            <table class="row" style="border-spacing: 0;border-collapse: collapse;padding: 0px;vertical-align: top;text-align: left;width: 100%;position: relative;display: block;">
                <tr style="padding: 0;vertical-align: top;text-align: left;">
                    <td class="wrapper offset-by-one" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-left: 50px;border-collapse: collapse !important;">

                        <table class="two columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 80px;">
                            <tr style="padding: 0;vertical-align: top;text-align: left;">
                                <td style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">
                                    <img src="<?php echo $_SERVER['EMAIL_IMG_FOLDER']; ?>/cadastro_06.jpg" alt="" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;width: auto;max-width: 100%;float: left;clear: both;display: block;">
                                </td>
                                <td class="expander" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0 !important;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;visibility: hidden;width: 0px;border-collapse: collapse !important;"></td>
                            </tr>
                        </table>

                    </td>
                    <td class="wrapper last" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-right: 0px;border-collapse: collapse !important;">

                        <table class="eight columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 380px;">
                            <tr style="padding: 0;vertical-align: top;text-align: left;">
                                <td style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">
                                    <h2 class="title-pink" style="color: #dd5661;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: 600;padding: 0;margin: 0;text-align: left;line-height: 1.3;word-break: normal;font-size: 14px;margin-bottom: 5px;">Olá!</h2>
                                    <p class="text-md" style="margin: 0;margin-bottom: 10px;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;padding: 0;text-align: left;line-height: 19px;font-size: 14px;">Obrigada por se cadastrar em nosso site!<br/><br/>
                                        <!--<a href="https://mariadebarro.com.br">mariadebarro.com.br</a>-->
                                    </p>
                                </td>
                                <td class="expander" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0 !important;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;visibility: hidden;width: 0px;border-collapse: collapse !important;"></td>
                            </tr>
                        </table>

                    </td>
                </tr>
            </table>

<!--            <table class="row" style="border-spacing: 0;border-collapse: collapse;padding: 0px;vertical-align: top;text-align: left;width: 100%;position: relative;display: block;">
                <tr style="padding: 0;vertical-align: top;text-align: left;">
                    <td class="wrapper last" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-right: 0px;border-collapse: collapse !important;">

                        <table class="row" style="border-spacing: 0;border-collapse: collapse;padding: 0px;vertical-align: top;text-align: left;width: 100%;position: relative;display: block;">
                            <tr style="padding: 0;vertical-align: top;text-align: left;">
                                <td class="wrapper last" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-right: 0px;border-collapse: collapse !important;">

                                    <table class="twelve columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 580px;">
                                        <tr style="padding: 0;vertical-align: top;text-align: left;">
                                            <td style="padding-bottom: 0;word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;"> 
                                                <a href="https://mariadebarro.com.br" target="_blank" style="color: #2ba6cb;text-decoration: none;"><img src="<?php echo $_SERVER['EMAIL_IMG_FOLDER']; ?>/acompanhamento_pedido_28.jpg" alt="" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;width: auto;max-width: 100%;float: left;clear: both;display: block;border: none;"></a>
                                            </td>
                                        </tr>
                                    </table>12/12/2014

                                </td>
                            </tr>
                        </table>

                    </td>
                </tr>
            </table>-->
            
            <table class="row" style="border-spacing: 0;border-collapse: collapse;padding: 0px;vertical-align: top;text-align: left;width: 100%;position: relative;display: block;">
                <tr style="padding: 0;vertical-align: top;text-align: left;">
                    <td class="wrapper last" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-right: 0px;border-collapse: collapse !important;">

                        <table class="twelve columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 589px;">
                            <tr style="padding: 0;vertical-align: top;text-align: left;">
                                <td style="padding-bottom: 0;word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;"> 
                                    <img src="<?php echo $_SERVER['EMAIL_IMG_FOLDER']; ?>/cadastro_11.jpg" alt="" usemap="#mariadebarro" width="589" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;width: auto;max-width: 100%;float: left;clear: both;display: block;">
                                    <map name="mariadebarro">
                                        <area share="rect" coords="125,18,457,60" alt="Clique aqui para acessar o site" href="https://www.mariadebarro.com.br" target="_blank"></area>
                                        <area share="rect" coords="90,123,308,142" alt="Facebook" href="https://www.facebook.com/mariadebarroacessorios" target="_blank"></area>
                                        <area share="rect" coords="337,123,481,143" alt="Instagram" href="http://instagram.com/mariadebarro" target="_blank"></area>
                                        <area share="rect" coords="0,157,588,298" alt="Maria de Barro" href="<?php echo $_SERVER['EMAIL_SITE']; ?>" target="_blank"></area>
                                    </map>
                                </td>
                            </tr>
                        </table>

                    </td>
                </tr>
            </table>

            <!-- container end below -->
        </td>
    </tr>
</table>
<?php
require("footer.phtml");
?>