
                        <table class="container" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: inherit;width: 580px;margin: 0 auto;">
                            <tr style="padding: 0;vertical-align: top;text-align: left;">
                                <td style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">

                                    <table class="row" style="border-spacing: 0;border-collapse: collapse;padding: 0px;vertical-align: top;text-align: left;width: 100%;position: relative;display: block;">
                                        <tr style="padding: 0;vertical-align: top;text-align: left;">
                                            <td class="wrapper last" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-right: 0px;border-collapse: collapse !important;">

                                                <table class="twelve columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 580px;">
                                                    <tr style="padding: 0;vertical-align: top;text-align: left;">
                                                        <td align="center" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">
                                                            <center style="width: 100%;min-width: 580px;">

                                                                <p style="text-align: center;margin-bottom: 10px;margin-top: 12px;margin: 0;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;padding: 0;line-height: 19px;font-size: 14px;">
                                                                    <a href="#" style="display: inline-block;color: #2ba6cb;text-decoration: none;">
                                                                        <img src="<?php echo $_SERVER['EMAIL_IMG_FOLDER']; ?>/acompanhamento_pedido_32.png" alt="" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;width: auto;max-width: 100%;float: left;clear: both;display: block;border: none;">
                                                                    </a>
                                                                    <a href="#" style="display: inline-block;color: #2ba6cb;text-decoration: none;">
                                                                        <img src="<?php echo $_SERVER['EMAIL_IMG_FOLDER']; ?>/acompanhamento_pedido_34.png" alt="" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;width: auto;max-width: 100%;float: left;clear: both;display: block;border: none;">
                                                                    </a>
                                                                    <a href="#" style="display: inline-block;color: #2ba6cb;text-decoration: none;">
                                                                        <img src="<?php echo $_SERVER['EMAIL_IMG_FOLDER']; ?>/acompanhamento_pedido_36.png" alt="" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;width: auto;max-width: 100%;float: left;clear: both;display: block;border: none;">
                                                                    </a>
                                                                </p>
                                                            </center>
                                                        </td>
                                                        <td class="expander" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0 !important;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;visibility: hidden;width: 0px;border-collapse: collapse !important;"></td>
                                                    </tr>
                                                </table>

                                            </td>
                                        </tr>
                                    </table>
                                    <hr style="color: #e5e5e5;background-color: #e5e5e5;height: 1px;border: none;">
                                    <table class="row" style="border-spacing: 0;border-collapse: collapse;padding: 0px;vertical-align: top;text-align: left;width: 100%;position: relative;display: block;">
                                        <tr style="padding: 0;vertical-align: top;text-align: left;">
                                            <td class="wrapper last" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-right: 0px;border-collapse: collapse !important;">

                                                <table class="twelve columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 580px;">
                                                    <tr style="padding: 0;vertical-align: top;text-align: left;">
                                                        <td align="center" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">
                                                            <center style="width: 100%;min-width: 580px;">
                                                                <!--<p style="text-align: left;color: #d2d2d2;font-weight: 300;font-size: 12px;margin: 0;margin-bottom: 10px;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;padding: 0;line-height: 19px;">Se você não deseja mais receber nossas novidades <a href="#" style="color: #c9c9c9;font-weight: 500;text-decoration: none;">cancele sua assinatura.</a><br>-->
                                                                <p style="text-align: left;color: #d2d2d2;font-weight: 300;font-size: 12px;margin: 0;margin-bottom: 10px;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;padding: 0;line-height: 19px;">A Maria de Barro é uma loja de acessórios femininos online que, através de suas facilidades na compra,<br>
                                                                    oferece produtos com qualidade e elegância com todo conforto.</p>
                                                            </center>
                                                        </td>
                                                        <td class="expander" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0 !important;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;visibility: hidden;width: 0px;border-collapse: collapse !important;"></td>
                                                    </tr>
                                                </table>

                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>

                    </center>
                </td>
            </tr>
        </table>
    </body>
</html>