<?php
require("header.phtml");
?>

<table class="container" style="background-color: #fff;margin-top: 25px;box-shadow: 0 0 0 3px #e9e9e9;border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: inherit;width: 589px;margin: 0 auto;">
    <tr style="padding: 0;vertical-align: top;text-align: left;">
        <td style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 8px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">

            <!-- content start -->
            <table class="row" style="border-spacing: 0;border-collapse: collapse;padding: 0px;vertical-align: top;text-align: left;width: 100%;position: relative;display: block;">
                <tr style="padding: 0;vertical-align: top;text-align: left;">
                    <td class="wrapper last" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-right: 0px;border-collapse: collapse !important;">

                        <table class="twelve columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 589px;">
                            <tr style="padding: 0;vertical-align: top;text-align: left;">
                                <td style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">
                                    <img src="<?php echo $_SERVER['EMAIL_IMG_FOLDER']; ?>/restreamento.jpg" alt="" style="float: none;margin: 0 auto 20px;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;width: auto;max-width: 100%;clear: both;display: block;">
                                </td>
                                <td class="expander" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0 !important;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;visibility: hidden;width: 0px;border-collapse: collapse !important;"></td>
                            </tr>
                        </table>

                    </td>
                </tr>
            </table>

            <table class="row" style="border-spacing: 0;border-collapse: collapse;padding: 0px;vertical-align: top;text-align: left;width: 100%;position: relative;display: block;">
                <tr style="padding: 0;vertical-align: top;text-align: left;">
                    <td class="wrapper offset-by-one" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-left: 50px;border-collapse: collapse !important;">

                        <table class="two columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 80px;">
                            <tr style="padding: 0;vertical-align: top;text-align: left;">
                                <td style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">
                                    <img src="<?php echo $_SERVER['EMAIL_IMG_FOLDER']; ?>/cadastro_06.jpg" alt="" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;width: auto;max-width: 100%;float: left;clear: both;display: block;">
                                </td>
                                <td class="expander" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0 !important;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;visibility: hidden;width: 0px;border-collapse: collapse !important;"></td>
                            </tr>
                        </table>

                    </td>
                    <td class="wrapper last" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-right: 0px;border-collapse: collapse !important;">

                        <table class="eight columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 380px;">
                            <tr style="padding: 0;vertical-align: top;text-align: left;">
                                <td style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;">
                                    <h2 class="title-pink" style="color: #dd5661;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: 600;padding: 0;margin: 0;text-align: left;line-height: 1.3;word-break: normal;font-size: 14px;margin-bottom: 5px;">Olá <?php echo $view_nome; ?>,</h2>
                                    <p class="text-md" style="margin: 0;margin-bottom: 10px;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;padding: 0;text-align: left;line-height: 19px;font-size: 14px;">
                                        <br/>a nossa equipe oferece esse serviço de rastreamento para que você possa acompanhar o status da sua compra! 
                                        <br/><br/>
                                        Caso deseje, você pode visualizar todos os status por meio da sua conta em nosso site.
                                        <br/><hr/>
                                        <label><b>Pedido de nº <?php echo $view_n_pedido; ?></b></label>
                                        <br/><hr/>
                                        <label><b>Data e hora <?php echo $view_timestamp; ?></b></label>
                                        <p>
                                            <strong>Situação: </strong><?php echo $view_status; ?>
                                        </p>
                                        <br/><hr/>
                                        <p>
                                            <strong>Anotações: </strong><?php echo $view_apontamento; ?>
                                        </p>
                                        <br/><hr/>
                                    </p>
                                 <br>
                                 <br>
                                <div><strong>* Não responder a este e-mail</strong></div><br/>
                                </td>
                                <td class="expander" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0 !important;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;visibility: hidden;width: 0px;border-collapse: collapse !important;"></td>
                            </tr>
                        </table>

                    </td>
                </tr>
            </table>

            <table class="row" style="border-spacing: 0;border-collapse: collapse;padding: 0px;vertical-align: top;text-align: left;width: 100%;position: relative;display: block;">
                <tr style="padding: 0;vertical-align: top;text-align: left;">
                    <td class="wrapper last" style="word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 10px 20px 0px 0px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;position: relative;padding-right: 0px;border-collapse: collapse !important;">

                        <table class="twelve columns" style="border-spacing: 0;border-collapse: collapse;padding: 0;vertical-align: top;text-align: left;margin: 0 auto;width: 589px;">
                            <tr style="padding: 0;vertical-align: top;text-align: left;">
                                <td style="padding-bottom: 0;word-break: break-word;-webkit-hyphens: auto;-moz-hyphens: auto;hyphens: auto;padding: 0px 0px 10px;vertical-align: top;text-align: left;color: #57564a;font-family: &quot;Helvetica&quot;, &quot;Arial&quot;, sans-serif;font-weight: normal;margin: 0;line-height: 19px;font-size: 14px;border-collapse: collapse !important;"> 
                                    <img src="https://www.mariadebarro.com.br/homolog/web-files/emails/images/cadastro_14.jpg" alt="" usemap="#mariadebarro" width="589" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;width: auto;max-width: 100%;float: left;clear: both;display: block;">
                                    <map name="mariadebarro">
                                        <area share="rect" coords="125,18,457,60" alt="Clique aqui para acessar o site" href="https://www.mariadebarro.com.br/pt/conta/login-cadastro/" target="_blank"></area>
                                        <area share="rect" coords="90,123,308,142" alt="Facebook" href="https://www.facebook.com/mariadebarroacessorios" target="_blank"></area>
                                        <area share="rect" coords="337,123,481,143" alt="Instagram" href="http://instagram.com/mariadebarro" target="_blank"></area>
                                        <area share="rect" coords="0,157,588,298" alt="Maria de Barro" href="https://www.mariadebarro.com.br" target="_blank"></area>
                                    </map>
                                </td>
                            </tr>
                        </table>

                    </td>
                </tr>
            </table>

            <!-- container end below -->
        </td>
    </tr>
</table>

<?php
require("footer.phtml");

